<?php
/* ============================================================
   DAIRY MANAGEMENT SYSTEM - ASSIGNMENT 12
   Shared page footer - File: php/includes/footer.php

   Closes the <main> that header.php opened and prints the last part
   of the page. Included at the end of every PHP page.
   ============================================================ */
?>
        <p>
            <a class="btn" href="register.php">PHP Register a Farmer</a>
            <a class="btn btn-light" href="profile.php">View PHP Profile</a>
        </p>

    </main>

    <footer>
        <p>Contact: Dairy Cooperative Society Office, Main Road, Village &nbsp;|&nbsp; Phone: 98765 43210</p>
        <p>&copy; 2026 Dairy Management System - College Web Development Project</p>
        <p>
            Assignment 12 (PHP) pages are generated by the server.
            Nothing on this page is stored in a database yet - that is
            Assignment 13.
        </p>
    </footer>

</body>
</html>