<?php
/* ============================================================
   DAIRY MANAGEMENT SYSTEM - ASSIGNMENT 12
   PAGE 2 of 3 : FARMER PROFILE (READS THE SESSION)
   File: php/profile.php

   This page does not accept any form data. Its whole job is to show
   what is stored in the session, which is the second half of the
   Assignment 12 session demonstration:

     register.php  ->  session_start() + $_SESSION[...] = ...
                  ->  header('Location: profile.php')
     profile.php   ->  session_start() + reading $_SESSION[...]

   The two files share nothing except the session, which proves that
   the session really does carry data from one page to the next.

   Run it with:  php -S localhost:8000     (inside the php/ folder)
   then open:   http://localhost:8000/profile.php
   ============================================================ */

/* ---------- STEP 0 : START THE SESSION AND LOAD THE HELPERS ---------- */

/* session_start() again. On this visit PHP finds the session file
   that the cookie of the browser points to, so $_SESSION already
   contains everything register.php stored. */
session_start();

require_once __DIR__ . '/includes/functions.php';

$pageTitle = 'PHP Farmer Profile';
$pageSection = 'profile';

require_once __DIR__ . '/includes/header.php';


/* ---------- STEP 1 : READ THE SESSION ---------- */

/* takeFlashMessage() returns the one-time message that register.php
   stored, and removes it from the session in the same call - that is
   why the green message disappears when the page is refreshed. */
$successMessage = takeFlashMessage();

/* The farmer of this session, or null when nobody has registered yet.
   The ?? operator keeps the page working when the key is missing. */
$profile = $_SESSION['farmer_profile'] ?? null;

/* Totals of every farmer registered in this visit, worked out with a
   foreach loop and the += operator. */
$totalMilk = 0;
$totalAmount = 0;

foreach (registeredFarmers() as $savedFarmer) {
    $totalMilk += $savedFarmer['milk'];
    $totalAmount += $savedFarmer['amount'];
}
?>

    <!-- ============ THE GREEN SUCCESS MESSAGE ============
         Shown once, straight after a successful POST. The text was
         built with the concatenation operator in register.php and
         carried here through the session. -->
    <?php if ($successMessage !== '') { ?>
    <p class="register-status form-message ok" id="php-flash-success">
        <?= safeText($successMessage) ?>
    </p>
    <?php } ?>

    <section>
        <h2>Farmer Profile</h2>

        <?php if ($profile === null) { ?>

            <!-- ============ EMPTY STATE ============
                 The visitor opened this page directly, or the session
                 was destroyed by logout.php. PHP says so clearly
                 instead of printing an empty profile. -->
            <p class="register-status form-message error">
                No farmer profile is stored in this session.
            </p>
            <p>
                <a class="btn" href="register.php">Register a farmer first</a>
                <a class="btn btn-light" href="logout.php">Go to logout</a>
            </p>

        <?php } else { ?>

            <!-- ============ THE PROFILE OF THE FARMER ============
                 Every value printed below was built by PHP with the
                 string functions of includes/functions.php. safeText()
                 is used on every typed value, so nothing a farmer typed
                 can turn into HTML code. -->
            <p class="centre-note">
                Record read from the PHP session on <?= safeText($profile['registered_at']) ?>
                &bull; this page was generated by the server, not by JavaScript
                &bull; the record is lost when the session ends (that is
                Assignment 13's job to solve)
            </p>

            <!-- <dl> = description list: <dt> is the label and <dd> is
                 the value that belongs to it. -->
            <dl class="profile-list">
                <dt>Farmer Code</dt>
                <dd><?= safeText($profile['code']) ?>
                    <span class="field-hint">(strtoupper() + substr() + str_pad() + ".")</span></dd>

                <dt>Farmer Name</dt>
                <dd><?= safeText($profile['name']) ?>
                    <span class="field-hint">(trim() + strtolower() + ucwords(),
                    <?= safeText($profile['name_length']) ?> characters counted by strlen())</span></dd>

                <dt>Mobile Number</dt>
                <dd><?= safeText($profile['mobile_display']) ?>
                    <span class="field-hint">(spaces and dashes removed with str_replace())</span></dd>

                <dt>Mobile (hidden)</dt>
                <dd><?= safeText($profile['mobile_masked']) ?>
                    <span class="field-hint">(str_repeat('*', 5) + substr())</span></dd>

                <dt>Email</dt>
                <dd><?= $profile['email'] === '' ? 'not given (this field is optional)' : safeText($profile['email']) ?>
                    <span class="field-hint">(strtolower() when it was given)</span></dd>

                <dt>Village / Address</dt>
                <dd><?= safeText($profile['village']) ?>
                    <span class="field-hint">(shortened to 18 characters:
                    <?= safeText($profile['village_short']) ?> with substr())</span></dd>

                <dt>Average Milk per Day</dt>
                <dd><?= safeText(number_format($profile['milk'], 1)) ?> litres</dd>

                <dt>Fat Percentage</dt>
                <dd><?= safeText(number_format($profile['fat'], 1)) ?> %</dd>

                <dt>Rate</dt>
                <dd><?= safeText(rateText($profile['rate'])) ?>
                    <span class="field-hint">(rateForFat() - the same rate board as Assignment 7)</span></dd>

                <dt>Daily Milk Value</dt>
                <dd>Rs <?= safeText(number_format($profile['amount'], 2)) ?>
                    <span class="field-hint">(litres x rate, formatted with number_format())</span></dd>

                <dt>Summary</dt>
                <dd><?= safeText($profile['summary']) ?></dd>
            </dl>

        <?php } ?>
    </section>

    <!-- ============ WHAT THE SESSION HOLDS ============
         These four blocks are printed by the same helper functions the
         header strip uses, so the page shows its own proof that the
         session is alive. -->
    <section>
        <h2>What This PHP Session Holds</h2>

        <div class="flex-row">
            <div class="flex-item">
                <h3>Session Status</h3>
                <p class="total-value"><?= farmerIsRegistered() ? 'OPEN' : 'EMPTY' ?></p>
                <p><?= farmerIsRegistered() ? 'A farmer profile is stored.' : 'No farmer profile is stored yet.' ?></p>
            </div>
            <div class="flex-item">
                <h3>Registrations</h3>
                <!-- The simple session value of this assignment. -->
                <p class="total-value"><?= registeredCount() ?></p>
                <p>$_SESSION['registration_count']</p>
            </div>
            <div class="flex-item">
                <h3>Milk in This Session</h3>
                <p class="total-value"><?= safeText(number_format($totalMilk, 1)) ?> L</p>
                <p>Added with a foreach loop and +=</p>
            </div>
            <div class="flex-item">
                <h3>Milk Value in This Session</h3>
                <p class="total-value">Rs <?= safeText(number_format($totalAmount, 2)) ?></p>
                <p>What the society would pay every day</p>
            </div>
        </div>
    </section>

    <!-- ============ EVERY FARMER OF THIS SESSION ============ -->
    <section>
        <h2>Every Farmer in This Session</h2>

        <div class="log-window">
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Farmer Code</th>
                        <th>Name</th>
                        <th>Mobile</th>
                        <th>Village</th>
                        <th>Milk (L)</th>
                        <th>Fat %</th>
                        <th>Rate (Rs)</th>
                        <th>Amount (Rs)</th>
                        <th>Registered At</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (registeredCount() === 0) { ?>
                    <tr>
                        <td colspan="10">Nothing stored in this session yet.</td>
                    </tr>
                    <?php } else { ?>
                        <?php $rowNumber = 1; ?>
                        <?php foreach (registeredFarmers() as $savedFarmer) { ?>
                        <tr>
                            <td><?= $rowNumber ?></td>
                            <td><?= safeText($savedFarmer['code']) ?></td>
                            <td><?= safeText($savedFarmer['name']) ?></td>
                            <td><?= safeText($savedFarmer['mobile_display']) ?></td>
                            <td><?= safeText($savedFarmer['village']) ?></td>
                            <td><?= safeText(number_format($savedFarmer['milk'], 1)) ?></td>
                            <td><?= safeText(number_format($savedFarmer['fat'], 1)) ?></td>
                            <td><?= safeText(number_format($savedFarmer['rate'], 2)) ?></td>
                            <td><?= safeText(number_format($savedFarmer['amount'], 2)) ?></td>
                            <td><?= safeText($savedFarmer['registered_at']) ?></td>
                        </tr>
                        <?php $rowNumber++; ?>
                        <?php } ?>
                    <?php } ?>
                </tbody>
            </table>
        </div>

        <p class="register-status">
            Remember: these rows exist only while the session is alive.
            Closing the browser, or using the PHP Logout link, deletes them
            for good.
        </p>

        <p>
            <a class="btn" href="register.php">Register Another Farmer</a>
            <a class="btn btn-light" href="logout.php">End This Session</a>
        </p>
    </section>

    <aside>
        <h3>Why does the profile still show the farmer?</h3>
        <ul>
            <li><code>session_start()</code> opens the session file of this visitor.</li>
            <li>The session cookie sent by the browser tells PHP which file to open.</li>
            <li><code>$_SESSION</code> is that file, read into an array.</li>
            <li>Nothing is written to a database, so the data ends with the session.</li>
            <li>Assignment 13 will replace the session with a MySQL table.</li>
        </ul>
    </aside>

<?php
require_once __DIR__ . '/includes/footer.php';